---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: iot-backend-mariadb
  labels:
    app: iot-backend
spec:
  selector:
    matchLabels:
      app: iot-backend
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iot-backend
        tier: mariadb
    spec:
      containers:
      - image: mariadb:10.3
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim