---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: iot-backend-mqtt-db-agent
  labels:
    app: iot-backend
    tier: mqtt-db-agent
spec:
  selector:
    matchLabels:
      app: iot-backend-mqtt-db-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iot-backend-mqtt-db-agent
    spec:
      containers:
      - image: pradeesi/mqtt_db_plugin:v2
        name: mqtt-db-agent
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-pass
              key: password