---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: iot-backend
spec:
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30306
  selector:
    app: iot-backend
    tier: mariadb
  type: "NodePort"