---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "iot-frontend-config"
  namespace: "default"
  labels:
    app: "iot-frontend"
data:
  BACKEND_HOST: "172.18.1.19"
  BACKEND_PORT: "30500"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "iot-frontend"
  namespace: "default"
  labels:
    app: "iot-frontend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "iot-frontend"
  template:
    metadata:
      labels:
        app: "iot-frontend"
    spec:
      containers:
      - name: "frontend-server"
        image: "eu.gcr.io/fwardz001-poc-ci1s/frontend_server:latest"
        env:
        - name: "BACKEND_HOST"
          valueFrom:
            configMapKeyRef:
              key: "BACKEND_HOST"
              name: "iot-frontend-config"
        - name: "BACKEND_PORT"
          valueFrom:
            configMapKeyRef:
              key: "BACKEND_PORT"
              name: "iot-frontend-config"
      - name: "nginx-srvr"
        image: "eu.gcr.io/fwardz001-poc-ci1s/nginx_srvr:latest"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "iot-frontend-hpa"
  namespace: "default"
  labels:
    app: "iot-frontend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "iot-frontend"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
